# SPDX-License-Identifier: GPL-2.0

# Use the absolute path of this Makefile to get the source directory.
CURRENT_DIR=$(dir $(abspath $(lastword $(MAKEFILE_LIST))))
GIT_PATH=$(CURRENT_DIR)/../../
GIT_BIN=/usr/bin/git
GIT=$(GIT_BIN) -C $(GIT_PATH)
ccflags-y	+= $(EXTRA_CFLAGS) -DCONFIG_EDGETPU_TELEMETRY_TRACE=1 \
		   -I$(CURRENT_DIR)/include

ifeq ($(shell $(GIT) rev-parse --is-inside-work-tree),true)
	GIT_REPO_STATE=$(shell ($(GIT) status --porcelain | grep -q .) && echo -dirty)
	ccflags-y	+= -DGIT_REPO_TAG=\"$(shell $(GIT) rev-parse --short HEAD)$(GIT_REPO_STATE)\"
endif

obj-$(CONFIG_ABROLHOS)	+= abrolhos.o

edgetpu-objs	:= edgetpu-async.o \
		   edgetpu-dmabuf.o \
		   edgetpu-domain-pool.o \
		   edgetpu-firmware-util.o \
		   edgetpu-firmware.o \
		   edgetpu-iremap-pool.o \
		   edgetpu-kci.o \
		   edgetpu-mailbox.o \
		   edgetpu-mapping.o \
		   edgetpu-sw-watchdog.o \
		   edgetpu-telemetry.o

abrolhos-objs	:= abrolhos-core.o \
		   abrolhos-debug-dump.o \
		   abrolhos-device-group.o \
		   abrolhos-device.o \
		   abrolhos-firmware.o \
		   abrolhos-fs.o \
		   abrolhos-iommu.o \
		   abrolhos-platform.o \
		   abrolhos-pm.o \
		   abrolhos-thermal.o \
		   abrolhos-usage-stats.o \
		   abrolhos-wakelock.o \
		   $(edgetpu-objs)

CFLAGS_abrolhos-fs.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-core.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-device.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-device-group.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-firmware.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-iommu.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-platform.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-pm.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-thermal.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-debug-dump.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-usage-stats.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-wakelock.o := -DCONFIG_ABROLHOS=1
