# SPDX-License-Identifier: GPL-2.0
__dtbo	:= $(sort $(gs101_raviole_overlays))
__dtbo	:= $(addprefix $(obj)/,$(__dtbo))

$(obj)/dtbo.img: $(__dtbo) FORCE
	$(call if_changed,mkdtimg)
always +=  $(obj)/dtbo.img
